services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "4096M"
      DIFFICULTY: "3"
      SPAWN_PROTECTION: "6"
    volumes:
      - "./data:/data"