services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "4096M"
      DIFFICULTY: "3"
      SPAWN_PROTECTION: "6"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: ${RCON_PORT}
    volumes:
      - "./data:/data"